### ISSUE TITLE
Форматирование. Раздел "Первые шаги"

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#12]
Тут так и задумывалось с большой буквы? Не нужно ли с маленькой? Или стоит отделить ковычками/как-то выделить?
Указать вы их можете либо в Lutris для конкретных игр, либо в Параметрах **Запуска игры** в Steam...

**Comment by ventureoo** [comment]
Да, так и задумывалось. Подразумевалось тем самым выделить название строки с параметрами запуска, но, действительно, нужно было добавить кавычки.
