### ISSUE TITLE
Форматирование предложения. Раздел "Превые шаги"

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#14]
Окончание предложения выглядит не согласовано. 

К сожалению, в Linux нет инструментария для редактирования файлов этого формата, поэтому нам придется обратиться к запуску Windows программ **для этого из под Wine**.

Варианты

1. Возможно стоит поставить точку после "программ" и начать новое предложение с "для этого из под Wine@", а в скобках уточнить об описании установки Wine в последующем разделе. Проблема, что тогда нужно будет согласовать с этим предложением "В качестве примера, мы установим и запустим данную (p.s. не реклама) программу при помощи Wine.".
2. Или возможно стоит просто указать в скобках "Для этого использовать (запускать из под) Wine".

**Comment by dewdpol** [comment]
Возможно я не правильно понял предложение

**Comment by ventureoo** [comment]
Я думаю достаточно убрать "для этого из" и оставить предложение в такой формулировке:

> К сожалению, в Linux нет инструментария для редактирования файлов этого формата, поэтому нам придется обратиться к запуску Windows программ под Wine.

**Comment by dewdpol** [comment]
Да так лучше
