### ISSUE TITLE
Полезное ПО: pam_usb

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#15]
В раздел полезного ПО возможно можно добавить Pam_USB. Данная программа возможно не очень соответствует общей цели ARU. Программа предназначена для создания из usb-flash своего рода ключ к системе или обеспечения дополнительной защиты, поскольку есть несколько режимов: использовать usb-flash вместо пароля при условии подключения (при отсутствии подключения нужно вводить пароль), требовать наличие подключенного usb-flash и ввод пароля.

Работающая версия:

https://github.com/mcdope/pam_usb

**Comment by dewdpol** [comment]
Версия в AUR не поддерживается

**Comment by ventureoo** [comment]
Действительно, не совсем по теме ARU. Но если в подразделе "Полезное ПО" наберется достаточно программ, то его можно будет вынести в отдельный, большой раздел куда можно будет добавлять разный по назначению софт без притязаний на тематику руководства. Сделать собственный пакет для AUR - не проблема, так что могу в скором времени добавить.

**Comment by dewdpol** [comment]
PKGBUILD для arch там есть, а вот в AUR устаревшая версия. С GitHub можно брать без проблем
