### ISSUE TITLE
Возможно ошибка? Раздел "Настройка параметров ядра"

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#24]
Тут идёт речь об использовании RAID? Выходит, если используется RAID приписывать данную команду "не нужно" или я не так понял?

raid=noautodetect - Отключает проверку на RAID во время загрузки. **Если вы его используете - прописывайте данный параметр.**

**Comment by ventureoo** [comment]
Если вы используете RAID, то конечно вам нужно оставлять включенным его автоопределение. То есть, да, в приведенном предложении пропущена частица "не".
