### ISSUE TITLE
Вопрос о plasma.

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#25]
В archlinux есть несколько пакетов kde plasma: plasma-wayland-session - пакет Wayland, plasma - полная сборка kde plasma со множеством пакетов, plasma-desktop - минимальный набор пакетов в котором нужно чистить минимум и как правило часть устанавливать отдельно. 
Часть пакетов, которую советуется удалять в ARU отсутствует в комплекте plasma-desktop. 

В связи с этим вопрос - не стоит ли добавить уточнение в оптимизацию окружения или рекомендацию по установке?

**Comment by ventureoo** [comment]
Если я правильно понял, то имеется в виду, что в ARU описаны команды по удалению "мусорных пакетов" которых нет в группе plasma-desktop?

**Comment by dewdpol** [comment]
По большей части да. Там нет многих пакетов
