### ISSUE TITLE
Уточнение флагов или Опечатка. Раздел "Файловые системы" 

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#26]
В оптимальных флагах говорится о том, что стоит указывать noatime, но в строке с оптимальными параметрами указано realtime?
Так же присутствует опечатка "relatime". Что именно подразумевалось?

rw,**relatime**,ssd,ssd_spread,space_cache=v2,max_inline=256,commit=600,nodatacow

**Comment by ventureoo** [comment]
Прежде всего, флаг `relatime` указан верно, он так и называется. Ошибка есть в его описании: не **real**time, а **relatime**.

См. `man 8 mount`
>        relatime
>            Update inode access times relative to modify or change time.
>            Access time is only updated if the previous access time was
>            earlier than the current modify or change time. (Similar to
>            noatime, but it doesn’t break mutt(1) or other applications
>            that need to know if a file has been read since the last time
>            it was modified.)

Указывать флаг `noatime` или нет - на свое усмотрение. По производительности он лучше остальных, к тому же работает для любой файловой системы. Но при этом может создавать проблемы в приложениях зависимых от точного указания времени файлов (в разделе об этом указано), ровным счёт как и `lazytime` (источников не укажу, раздел был написан @Almarus, он и должен уточнять). В оптимальных флагах `relatime` был указан потому, что он наиболее беспроблемный, и как следствие теперь начиная с версии ядра Linux 2.6.30 используется по умолчанию.

Вообщем да, раздел надо бы переписать, ибо много несостыковок.

**Comment by ventureoo** [comment]
Сейчас немного переписал раздел, возможно стало понятнее, и теперь разъяснения написаны в правильном порядке.

**Comment by dewdpol** [comment]
Да выходит, что опечатка была в другом месте
