### ISSUE TITLE
Опечатка? Раздел "Кастомные ядра..."

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#29]
Верно ли указан флаг? Тут разве не "-O2"?

_complierlevel="2" - Задает степень оптимизации компиляции ядра. Лучше всего выбирать "2", **т.е. сборку с -O3 флагом** (макс. производительность).

**Comment by ventureoo** [comment]
Нет, значение указано верно, в `customization.cfg` [двойка соответствует флагу -O3](https://github.com/Frogging-Family/linux-tkg/blob/master/customization.cfg#L177). Но спасибо что напомнили, ибо лучше сменить его на `-O2` (т.е. значение "1").

См. https://www.phoronix.com/scan.php?page=news_item&px=No-O3-For-Linux-Kernel, https://github.com/ventureoo/ARU/commit/0bba7689c8a8c40ac9119f6b48ff8fb454d39148
