### ISSUE TITLE
Ошибка в "Настройка makepkg.conf" Базовое ускорение системы

### ISSUE THREAD

**Issue by holydrug** [ventureoo/ARU#3]
У вас написано это:
CFLAGS="-march=native -mtune=native -O3 -pipe -fno-plt -fexceptions \
      -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
      -fstack-clash-protection -fcf-protection"
CXXFLAGS=”$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
RUSTFLAGS="-C opt-level=3"
MAKEFLAGS="-j$(nproc) -l$(nproc)"
OPTIONS=(strip docs !libtool !staticlibs emptydirs zipman purge !debug lto)

Стоит не тот символ в 
CXXFLAGS=”$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"

что приводит к ошибке, должно быть:
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"

или нет?

**Comment by ventureoo** [comment]
Здравствуйте. Можно уточнить, какой именно символ был пропущен? Просто для меня все три строки что вы привели одинаковы.

В `makepkg.conf` по умолчанию установлено тоже самое значение:

https://github.com/archlinux/svntogit-packages/blob/packages/pacman/trunk/makepkg.conf#L44

**Comment by ventureoo** [comment]
Извините, да, я понял вас, `CXXFLAGS` начинается не с тех кавычек.
