### ISSUE TITLE
Уточнение. "Оптимизация рабочих окружений..."

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#39]
Возможно стоит добавить уточнение - в случае, если они не были удалены:

Служба вернется в строй после перезагрузки.

**Comment by ventureoo** [comment]
Не совсем понятно, как они могут быть удалены. Даже со старый способом с переименованием библиотек их все ещё можно было вернуть простой переустановкой пакета `gnome-settings-daemon`.

**Comment by dewdpol** [comment]
Выше просто было уточнение, что если что-то было удалено первым способом

**Comment by ventureoo** [comment]
Не уверен, что это требуется. Старый способ уже давно нигде не описывается, в архивных выпусках из Google Docs его тоже нет.
