### ISSUE TITLE
Ошибочка

### ISSUE THREAD

**Issue by UnixLudi0** [ventureoo/ARU#47]
![image](https://user-images.githubusercontent.com/95374315/149390988-9c0e8994-70c9-4978-b77d-1780a50c40b4.png)

**Comment by UnixLudi0** [comment]
Также в manjaro например нету пакета grub-customizer

**Comment by ventureoo** [comment]
Прежде всего, у нас руководство по оптимизации Arch Linux. То, что в Manjaro убрали grub-customizer никак не отменяет ручного редактирования файла `/etc/default/grub`. Выше указанная опечатка уже была исправленна в https://ventureoo.github.io/ARU/ коммитом https://github.com/ventureoo/ARU/commit/0605f9399a575ec17563c57f85ea0fd15fb51392 и будет отсутствовать в следующем стабильном выпуске ARU. Спасибо.
