### ISSUE TITLE
Опечатка

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#5]
Небольшая опечатка в разделе "Базовое ускорение системы"
1.5.1 rng-tools - демон, что также следит **на** энтропией системы

**Comment by ventureoo** [comment]
Исправлено с https://github.com/ventureoo/ARU/commit/d9118d2b334d069ebb1592d52ed33c9cdffd6cbd. Благодарю.

**Comment by dewdpol** [comment]
Нашел еще одну опечатку (Это **измнение** профиля питания видеокарты... в разделе "Первые шаги"
