### ISSUE TITLE
File-systems

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#54]
В html было решено не использовать подразделы в "Оптимизации файловой системы" или что-то пошло не так?

**Comment by ventureoo** [comment]
Не вижу в этом смысла. Руководство и так написано об оптимизации системы и всем что с ней связано, лишний раз уточнять это в названиях разделов нет смысла.

**Comment by dewdpol** [comment]
Имелось в виду, что структура содержания в разделе не полная - переходы на подразделы отсутствуют, если это так задумано, то вопросов нет

**Comment by dewdpol** [comment]
Сейчас у меня появились подразделы...

**Comment by ventureoo** [comment]
@dewdpol Да, исправлено коммитом https://github.com/ventureoo/ARU/commit/94f16ceb12a8efb8ba76205812e71a8e36dddf13.
