### ISSUE TITLE
de-optimizations: kwin-lowlatency

### ISSUE THREAD

**Issue by ventureoo** [ventureoo/ARU#57]
Был давно в ARU, но затем был убран из-за заморозки разработки. Теперь проект опять воскрес.
https://github.com/tildearrow/kwin-lowlatency

**Comment by dewdpol** [comment]
Я давно как-то пробовал использовать, но разницы не заметил

**Comment by ventureoo** [comment]
@dewdpol Разница есть, просто не такая заметная.

**Comment by dewdpol** [comment]
@ventureoo у меня Nvidia, но сложно сказать. Возможно не сильно значительная
