### ISSUE TITLE
Forcing the use of AMD SAM

### ISSUE THREAD

**Issue by ventureoo** [ventureoo/ARU#62]
Добавить инструкцию по включению AMD SAM. Главная оптимизация для старых видеокарт AMD.

@Almarus

**Comment by ventureoo** [comment]
Ждём видео версию от @Almarus.

**Comment by dewdpol** [comment]
Так SAM это же AMD + AMD, в противных случаях это ResizeBar?

**Comment by ventureoo** [comment]
@dewdpol Не совсем понял. Да, эта технология работает только для AMD. Для NVIDIA нужно использовать их реализацию Resizable Bar, которая доступна только с серии RTX 30.

**Comment by dewdpol** [comment]
@ventureoo насколько знаю с процессорами Intel это тоже нет работает. В данном случае тоже ResizeBar, насколько мне известно, хотя не уверен на счёт linux

**Comment by dewdpol** [comment]
@ventureoo если технология будет представлена для проц AMD и видеокарта AMD, то вопросов нет, остальное изложил выше

**Comment by ventureoo** [comment]
@dewdpol Технология может работать с любыми процессорами если у них есть поддержка инструкции PCIe `full-rate _pdep_u32/64`. Для процессоров Intel это примерно начиная с поколения Haswell. Для видеокарт серии 6000 SAM просто задействован из коробки, но это не значит что на карточках помладше она работать не будет. Собственно, для этого и написан данный раздел, чтобы указать людям что такую технологию можно задействовать и на старом железе. Основные требования идут к материнской плате - поддерживает она или нет. Если в UEFI есть настройки "Above 4G Decoding" и "Re-Size BAR Support" значит технология скорее всего будет работать. 
Раньше на конфигурациях с Intel судя по всему были проблемы, но с последними версиями Mesa поддержка процессоров Intel уже лучше.
https://gitlab.freedesktop.org/mesa/mesa/-/issues/5282

**Comment by ventureoo** [comment]
Навесил побольше предупреждений.
