### ISSUE TITLE
userful-programs: Heroic Games Launcher

### ISSUE THREAD

**Issue by ventureoo** [ventureoo/ARU#64]
Открытый лаунчер для Epic Games Store.

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher

**Comment by dewdpol** [comment]
Проблема лаунчера в том, что он частично работает через браузер, из-за раньше необходимо было проходить проверку капчей и довольно часто

**Comment by ventureoo** [comment]
@dewdpol Понятно, что такие программы не годятся для взаимодействия с сервисами Epic Games, вроде управления аккаунта и получения бесплатных игр. Но они позволяют достаточно хорошо управлять играми которые вы уже имеете в библиотеке, и которые можно установить и запустить через Wine.

**Comment by dewdpol** [comment]
@ventureoo в плане запуска данный лаунчер наверное удобнее, чем официальный через lutris

**Comment by dewdpol** [comment]
Похоже косяк с капчей исправили, теперь не требует при добавлении игры через launcher

**Comment by ventureoo** [comment]
@dewdpol Это хорошо. Мне тоже нужно будет его проверить.

**Comment by dewdpol** [comment]
В heroic games launcher добавлена поддержка gog

**Comment by ventureoo** [comment]
Как уже обсуждали в телеграмм канале, пока обойдемся упоминанием интеграции с Lutris.
