### ISSUE TITLE
userful-progams: Minigalaxy

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#68]
Подобие Heroes Games Launcher для EpicGames есть для GOG, но я его не проверял https://github.com/sharkwouter/minigalaxy

**Comment by ventureoo** [comment]
Имхо, я бы рекомендовал использовать консольные lgogdownloader и legendary, ибо с ними на мой взгляд меньше всего проблем. Но для неискушенных пользователей это может показаться неудобным.

**Comment by dewdpol** [comment]
Для тех кто недавно перешёл с windows или просто не хочет лесть в терминал - это точно не подойдёт.

**Comment by ventureoo** [comment]
Как уже обсуждали в телеграмм канале, пока обойдемся упоминанием интеграции с Lutris.
