### ISSUE TITLE
Решение проблемы с зависанием графики Vega 11

### ISSUE THREAD

**Issue by Vochatrak-az-ezm** [ventureoo/ARU#72]
На Linux есть неприятный баг, со случайным зависанием системы с интегрированными в процессор видеоядрами. 
Наиболее часто баг проявляется на процессорах **Ryzen 2XXXG** и реже на **Ryzen 3XXXG**.
Что бы победить этот баг необходимо добавить в **/etc/default/gr**ub в строку **GRUB_CMDLINE_LINUX_DEFAULT=**
Следующее:
`mdgpu.gttsize=8192 amdgpu.lockup_timeout=1000 amdgpu.gpu_recovery=1 amdgpu.noretry=0 amdgpu.ppfeaturemask=0xfffd3fff amdgpu.deep_color=1 systemd.unified_cgroup_hierarchy=true`
И на всякий случай в **/etc/environment**
`AMD_DEBUG=nodcc`
После этого случайные зависания видеоядра замечены небыли.

Стоит добавить эту информацию в "ARU", так как подобный баг может проявляться и на более новых процессорах с видеоядром **Vega**

**Comment by ventureoo** [comment]
Спасибо за информацию. Проблема встречается только у открытых драйверов, или также актуальна и для проприетарных (AMDGPU PRO)?

**Comment by Vochatrak-az-ezm** [comment]
Это баг ядерной части драйвера.
Соответственно проявляется на всех вариантах драйверов.

**Comment by ventureoo** [comment]
Ясно, сейчас добавлю.
