### ISSUE TITLE
Форматирование. Раздел "Первые шаги"

### ISSUE THREAD

**Issue by dewdpol** [ventureoo/ARU#8]
Возможно стоит исправить одно из двух:
Указать вы их можете **либо** в Lutris для конкретных игр **или** в "Свойствах игры" в Steam.

Возможно так:
1. Убрать "либо"
2. Заменить "или" на "либо"

**Comment by ventureoo** [comment]
Думаю, второй вариант будет предпочтительнее с синтаксической точки зрения, ибо становиться яснее разделение на способ для Steam, и на способ для Lutris. Благодарю!
